// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuq3S6iLdIs83dTCi90AEfZ9mwuKukmxc',
    appId: '1:160594847503:web:098cc396599a3cd820807a',
    messagingSenderId: '160594847503',
    projectId: 'practicaconexion-2dbb1',
    authDomain: 'practicaconexion-2dbb1.firebaseapp.com',
    storageBucket: 'practicaconexion-2dbb1.appspot.com',
    measurementId: 'G-Y5S4X0NEVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUj4ivobDrItOq2yYEuXnYqijOoNSMAz0',
    appId: '1:160594847503:android:f969d598c39c34f920807a',
    messagingSenderId: '160594847503',
    projectId: 'practicaconexion-2dbb1',
    storageBucket: 'practicaconexion-2dbb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ6DKbWmE7ReGo-yMQt6vb0Wvljn76CrI',
    appId: '1:160594847503:ios:5adeec244059908a20807a',
    messagingSenderId: '160594847503',
    projectId: 'practicaconexion-2dbb1',
    storageBucket: 'practicaconexion-2dbb1.appspot.com',
    iosClientId: '160594847503-bj4fncu6frpqvnufua7c8amuhlhr4fn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.google',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ6DKbWmE7ReGo-yMQt6vb0Wvljn76CrI',
    appId: '1:160594847503:ios:5111f4b9a33c549120807a',
    messagingSenderId: '160594847503',
    projectId: 'practicaconexion-2dbb1',
    storageBucket: 'practicaconexion-2dbb1.appspot.com',
    iosClientId: '160594847503-obalfu85fqekdm7l6de4tlea4j8sri4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.google.RunnerTests',
  );
}
